### ISSUE TITLE
如何设置多用户

### ISSUE THREAD

**Issue by jcx70100** [tracyone/v2ray.fun#22]
您好，请问v2ray怎么设置多用户呢？可以考虑加入多用户的选项吗？

**Comment by tracyone** [comment]
哈，我得研究下

**Comment by rickycm** [comment]
支持加入多用户支持！
是不是手动改生成的配置文件也要以？

**Comment by Zhai2333** [comment]
如使用多用户，一个代替方案是 Jrony/multi-v2ray ，并且手动更改配置会导致无法读取出错。

**Comment by rickycm** [comment]
Jrony/multi-v2ray 我也试过了，我这里一直报错：

1.更改email

2.更改UUID

3.更改alterID

4.更改主端口

5.更改传输方式

6.更改TLS设置

7.更改广告拦截功能

8.更改动态端口

9.更改Shadowsocks加密方式

10.更改Shadowsocks密码

请输入数字选择功能： 4

Traceback (most recent call last):
File "/usr/local/multi-v2ray/config_modify/port.py", line 3, in 
import read_json
ImportError: No module named 'read_json'
Traceback (most recent call last):
File "/usr/local/multi-v2ray/base_util/open_port.py", line 4, in 
import read_json
ImportError: No module named 'read_json'

**Comment by rickycm** [comment]
> 如使用多用户，一个代替方案是 Jrony/multi-v2ray ，并且手动更改配置会导致无法读取出错。

刚才试着手动改了配置文件，看来是可以的
在/etc/v2ray/config.json 里面加上多个用户信息
